// Generated by CoffeeScript 1.9.3
var Model, racer,
  hasProp = {}.hasOwnProperty;

racer = require('k-model');

Model = racer.Model;

module.exports = function(app, options) {
  var Flash;
  if (options == null) {
    options = {};
  }
  Flash = (function() {
    var middleware, originalRouter;

    function Flash() {}

    Flash.prototype.view = __dirname;

    app.on('render', function(app) {
      var data, flashq, i, len, model, obj, type;
      model = app.model;
      flashq = model.get('_flash.flashq') || {};
      if (flashq) {
        for (type in flashq) {
          data = flashq[type];
          if (data instanceof Array) {
            for (i = 0, len = data.length; i < len; i++) {
              obj = data[i];
              if (typeof obj.msg === 'string' && model.toast && (options.useToast || obj.toast)) {
                model.toast(type, obj.msg);
              } else {
                model.root.push("_page.flash." + type, obj.msg);
              }
            }
          } else {
            model.root.set("_page.flash." + type, data);
          }
        }
      }
      return model.del('_flash.flashq');
    });

    Model.prototype.flash = function(type, msg, useToast) {
      var key, ref, ref1, ref2, t, val;
      if (typeof type === 'object') {
        useToast = msg;
        for (key in type) {
          if (!hasProp.call(type, key)) continue;
          val = type[key];
          t = key;
          msg = val;
        }
        type = t;
      }
      if (type && msg) {
        if ((ref = this.data) != null ? (ref1 = ref.$controller) != null ? (ref2 = ref1.req) != null ? ref2.flash : void 0 : void 0 : void 0) {
          return this.data.$controller.req.flash(type, msg);
        } else {
          return this.root.push("_flash.flashq." + type, {
            msg: msg,
            toast: useToast
          });
        }
      }
    };

    originalRouter = app.router;

    middleware = function(req, res, next) {
      var i, len, model, msg, msgs, obj, ref, type;
      if (req.flash && req.session) {
        model = req.getModel();
        msgs = req.flash();
        for (type in msgs) {
          ref = msgs[type];
          for (i = 0, len = ref.length; i < len; i++) {
            msg = ref[i];
            if (typeof msg === 'string') {
              model.push("_flash.flashq." + type, {
                msg: msg
              });
            } else {
              for (obj in msg) {
                model.set("_flash.flashq." + type + "." + obj, msg[obj]);
              }
            }
          }
        }
      }
      return (originalRouter())(req, res, next);
    };

    app.router = function() {
      return middleware;
    };

    return Flash;

  })();
  return app.component(Flash);
};
